name: Rebuild and Deploy GitHub Pages

on:
  schedule:
    # Runs at 00:00 every Sunday
    - cron: '0 0 * * 0'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Set to your project's required Ruby version

    - name: Install dependencies
      run: |
        bundle install

    - name: Build the site (Jekyll)
      run: |
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Set this to your site's build directory
